Repository VIVelev/nujo, pull requests merged in 2020-05, with the labels that each got.

#31 Feature/autodiff test
  .github/workflows/codecov.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  docs/utils/data/dataset_iterator.html
  examples/nn_linear.py
  nujo/autodiff/_functions/_elementary.py
  nujo/utils/data/dataset_iterator.py
  tests/test_autodiff/test_autodiff.py
  tests/test_autodiff/test_node.py
  tests/test_autodiff/test_tensor.py
  tests/test_flow.py
  tests/test_math/test_aggregate.py
  tests/test_math/test_scalar.py
  tests/test_nn/test_activations.py
  tests/test_objective/test_qualitative.py
  tests/test_objective/test_quantitative.py
Labels: enhancement

#33 Feature/dataset gimmicks
  README.md
  docs/utils/data/dataset.html
  docs/utils/data/dataset_iterator.html
  docs/utils/data/dataset_loader.html
  docs/utils/data/index.html
  nujo/utils/data/dataset.py
  nujo/utils/data/dataset_iterator.py
  nujo/utils/data/dataset_loader.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/test_utils/test_data/__init__.py
  tests/test_utils/test_data/test_dataset_loader.py
Labels: enhancement

#35 Merge 'feature/fix-docstring' into 'develop'
  CONTRIBUTING.md
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/flow.html
  docs/index.html
  docs/math/aggregate.html
  docs/nn/layers.html
  docs/optim/optimizer.html
  docs/optim/optimizers.html
  nujo/autodiff/_node.py
  nujo/autodiff/function.py
  nujo/autodiff/tensor.py
  nujo/flow.py
  nujo/math/aggregate.py
  nujo/optim/optimizer.py
  nujo/optim/optimizers.py
Labels: documentation

#36 Automatic documentation generation
  .github/workflows/gendocs.yml
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/modes.html
  docs/autodiff/tensor.html
  docs/flow.html
  docs/gendocs.py
  docs/index.html
  docs/init/basic.html
  docs/init/index.html
  docs/init/random.html
  docs/math/aggregate.html
  docs/math/index.html
  docs/math/scalar.html
  docs/nn/activations.html
  docs/nn/index.html
  docs/nn/layers.html
  docs/objective/index.html
  docs/objective/loss.html
  docs/objective/qualitative.html
  docs/objective/quantitative.html
  docs/optim/index.html
  docs/optim/optimizer.html
  docs/optim/optimizers.html
  docs/utils/data/dataset.html
  docs/utils/data/dataset_iterator.html
  docs/utils/data/dataset_loader.html
  docs/utils/data/index.html
  docs/utils/data/nujo_dir.html
  docs/utils/index.html
  docs/utils/viz/computation_graph_plotter.html
  docs/utils/viz/index.html
  poetry.lock
Labels: documentation, enhancement

#37 Feature/gendocs fix
  .github/workflows/gendocs.yml
  docs/nn/layers.html
  docs/optim/optimizers.html
  nujo/optim/optimizers.py
Labels: fix

#38 Feature/generators optimization
  .github/workflows/codecov.yml
  .github/workflows/test.yml
  docs/flow.html
  docs/index.html
  docs/optim/optimizer.html
  nujo/autodiff/_functions/_elementary.py
  nujo/autodiff/_node.py
  nujo/autodiff/_utils.py
  nujo/flow.py
  nujo/optim/optimizer.py
  tests/conftest.py
  tests/test_flow.py
  tests/test_optim/test_optimizers.py
  tests/test_utils/test_data/test_dataset_loader.py
Labels: enhancement

#39 Feature/nujo profiler
  .gitignore
  tools/README.md
  tools/decorators.py
  tools/profiler.py
Labels: enhancement

#40 Feature/mnist example
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/index.html
  docs/nn/index.html
  docs/nn/layers.html
  examples/README.md
  examples/mnist_feed_forward_nn.py
  nujo/autodiff/_functions/_activations.py
  nujo/autodiff/tensor.py
  nujo/nn/__init__.py
  nujo/nn/layers.py
  tests/test_nn/test_activations.py
Labels: documentation, enhancement, fix

#41 Feature/hash map cache storage
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/index.html
  docs/math/aggregate.html
  docs/math/scalar.html
  examples/nn_linear.py
  nujo/autodiff/function.py
  nujo/autodiff/tensor.py
  nujo/math/aggregate.py
  nujo/math/scalar.py
  poetry.lock
  tests/test_autodiff/test_tensor.py
  tests/test_math/test_aggregate.py
  tests/test_optim/test_optimizers.py
  tools/profiler.py
Labels: enhancement

#42 Feature/dynamic def static eval docs
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/modes.html
  docs/autodiff/tensor.html
  docs/flow.html
  docs/index.html
  docs/init/basic.html
  docs/objective/loss.html
  docs/objective/qualitative.html
  docs/objective/quantitative.html
  docs/optim/optimizer.html
  docs/optim/optimizers.html
  nujo/autodiff/function.py
  nujo/autodiff/modes.py
  nujo/autodiff/tensor.py
  nujo/flow.py
  nujo/init/basic.py
  nujo/objective/loss.py
  nujo/objective/qualitative.py
  nujo/objective/quantitative.py
  nujo/optim/optimizer.py
  poetry.lock
Labels: documentation, fix

#43 Feature/pre release refactoring
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/index.html
  docs/init/basic.html
  nujo/autodiff/_functions/_activations.py
  nujo/autodiff/function.py
  nujo/autodiff/tensor.py
  nujo/init/basic.py
  tests/test_autodiff/test_functions.py
  tests/test_autodiff/test_tensor.py
  tests/test_math/test_aggregate.py
Labels: enhancement, fix

#45 Feature/autodiff shape manipulations
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/flow.html
  docs/index.html
  docs/nn/layers.html
  nujo/autodiff/_functions/_activations.py
  nujo/autodiff/_functions/_aggregate.py
  nujo/autodiff/_functions/_elementary.py
  nujo/autodiff/_functions/_transform.py
  nujo/autodiff/tensor.py
  nujo/nn/_transform.py
  nujo/nn/layers.py
  poetry.lock
  tests/test_autodiff/test_tensor.py
  tmp.py
Labels: enhancement

#46 Feature/backward acum grad func
  .github/workflows/test.yml
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/modes.html
  docs/autodiff/tensor.html
  docs/index.html
  docs/math/scalar.html
  docs/nn/layers.html
  examples/mnist_feed_forward_nn.py
  examples/nn_linear.py
  nujo/autodiff/_functions/_activations.py
  nujo/autodiff/_functions/_aggregate.py
  nujo/autodiff/_functions/_elementary.py
  nujo/autodiff/_functions/_transform.py
  nujo/autodiff/_node.py
  nujo/autodiff/function.py
  nujo/autodiff/modes.py
  nujo/autodiff/tensor.py
  nujo/math/scalar.py
  nujo/nn/_transform.py
  nujo/nn/layers.py
  poetry.lock
  tests/test_autodiff/test_functions.py
  tests/test_autodiff/test_node.py
  tests/test_autodiff/test_tensor.py
  tmp.py
Labels: enhancement
