Repository VIVelev/nujo, pull requests merged in 2020-06, with the labels that each got.

#47 Feature/conv2d layer
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/index.html
  docs/nn/layers.html
  nujo/autodiff/_functions/_transform.py
  nujo/nn/layers.py
Labels: enhancement

#48 Feature/cache fixes
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/autodiff/tensor.html
  docs/index.html
  nujo/autodiff/_functions/_activations.py
  nujo/autodiff/_functions/_transform.py
  nujo/autodiff/function.py
  nujo/autodiff/tensor.py
Labels: fix

#51 Feature/softmax args
  docs/nn/activations.html
  nujo/autodiff/_functions/_activations.py
  nujo/nn/activations.py
Labels: enhancement

#50 Feature/flow of flows support
  docs/flow.html
  docs/index.html
  docs/nn/activations.html
  docs/nn/layers.html
  docs/objective/loss.html
  docs/objective/qualitative.html
  docs/objective/quantitative.html
  docs/optim/optimizer.html
  nujo/flow.py
  nujo/optim/optimizer.py
  poetry.lock
  tests/test_flow.py
  tests/test_optim/test_optimizers.py
Labels: enhancement, fix

#49 Feature/trigonometric funcs
  nujo/autodiff/_functions/_trigonometric.py
  tests/test_autodiff/test_functions/test_elementary.py
  tests/test_autodiff/test_functions/test_trigonometric.py
Labels: enhancement

#52 Feature/padding layer
  .github/workflows/gendocs.yml
  docs/autodiff/function.html
  docs/autodiff/index.html
  docs/flow.html
  docs/index.html
  docs/nn/layers.html
  nujo/autodiff/_functions/_transform.py
  nujo/nn/layers.py
Labels: enhancement

#55 Feature/conv dilation
  docs/nn/layers.html
  nujo/_cache.py
  nujo/autodiff/_functions/_transform.py
  nujo/nn/layers.py
Labels: enhancement

#57 Feature/trimming the fat
  CONTRIBUTING.md
  README.md
  docs/utils/computation_graph_plotter.html
  docs/utils/data/dataset.html
  docs/utils/data/dataset_iterator.html
  docs/utils/data/dataset_loader.html
  docs/utils/data/index.html
  docs/utils/data/nujo_dir.html
  docs/utils/flow_serialization.html
  docs/utils/index.html
  docs/utils/viz/index.html
  examples/graph_visualization.py
  examples/mnist_feed_forward_nn.py
  examples/nn_linear.py
  nujo/utils/__init__.py
  nujo/utils/computation_graph_plotter.py
  nujo/utils/data/__init__.py
  nujo/utils/data/dataset.py
  nujo/utils/data/dataset_iterator.py
  nujo/utils/data/dataset_loader.py
  nujo/utils/data/nujo_dir.py
  nujo/utils/flow_serialization.py
  nujo/utils/viz/__init__.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/test_utils/test_data/__init__.py
  tests/test_utils/test_data/test_dataset_loader.py
  tools/decorators.py
  tools/profiler.py
Labels: fix
